N-Queen DP 

In [1]:
import numpy as np

In [2]:
N= 8 

In [3]:
board_state_memory = {} 
#dict to cache our results
#For every state, we'll cache if the board is safe or not

In [4]:
#board is 2-D N*N array all initalized to 0s
board = np.zeros((N,N), np.int8)

In [5]:
board
#0 represents empty
#1 represents queen placed at that location

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [6]:
#fnx to represent our board in string form
def create_board_string(board):
    board_string = ""
    for i in range(N):
        for j in range(N):
            board_string += str(board[i][j])
    return board_string
        

In [7]:
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [8]:
#create copy of board for testing purpose
board_copy = board.copy()
board_copy[3][0] = 1
board_copy[3][1] = 1


In [9]:
print(board_copy)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [10]:
create_board_string(board_copy)

'0000000000000000000000001100000000000000000000000000000000000000'

In [11]:
def is_board_safe(board):
    board_key = create_board_string(board)
    
    if board_key in board_state_memory:
        print("Using cached information")
        return board_state_memory[board_key]
    
    #board is safe if there is only 1 queen in row
    row_sum = np.sum(board, axis = 1)
    if len(row_sum[np.where(row_sum>1)]) >0:
       board_state_memory[board_key] = False
       return False
       
    
    #board is safe if there is only 1 queen in column
    col_sum = np.sum(board, axis = 0)
    if len(col_sum[np.where(col_sum>1)]) >0:
       board_state_memory[board_key] = False
       return False
    
    diags = [board[::-1,:].diagonal(i) for i in range(-board.shape[0]+1,board.shape[1] )]
    
    diags.extend(board.diagonal(i) for i in range(board.shape[1]-1, -board.shape[0], -1))
    
    for diag in diags:
        if np.sum(diag)>1:
            board_state_memory[board_key] = False
            return False
        
    board_state_memory[board_key] = True
    return True
    
            

In [12]:
#Test have more than 1 queen in same row
board_copy = board.copy()
board_copy[2][1]=1
board_copy[2][4]=1

In [13]:
board_copy

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [14]:
is_board_safe(board_copy)

False

In [15]:
#Test have more than 1 queen in same column
board_copy = board.copy()
board_copy[2][3]=1
board_copy[5][3]=1

In [16]:
board_copy

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [17]:
is_board_safe(board_copy)

False

In [18]:
#Test have more than 1 queen in same diagonal
board_copy = board.copy()
board_copy[1][2]=1
board_copy[2][3]=1

In [19]:
board_copy

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [20]:
is_board_safe(board_copy)

False

In [21]:
#Test for safe board
board_copy = board.copy()
board_copy[1][2]=1
board_copy[4][6]=1

In [22]:
board_copy

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [23]:
is_board_safe(board_copy)

True

In [24]:
#recursive algo to place queens
def place_queen(board, column):
    
    if column>=N:
        return True #means for each column queen has been set
    for row in range(N):
        board[row][column] =1
        
        safe = False
        if is_board_safe(board):
            safe = place_queen(board, column+1)
            
        if not safe:
            board[row][column] = 0
        else:
            break
    
    return safe

In [25]:
board = np.zeros((N,N), np.int8)
placed = place_queen(board, 0)
print(placed)

True


In [26]:
board

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)